import Head from "next/head";
import styles from "../styles/Home.module.css";
import { UltraWallet } from "../components/UltraWallet";
import React from "react";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Wallet Auth</h1>
        <Link href="/app">Enter</Link>
      </main>
    </div>
  );
}
